version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run:
          name: Gradle build
          command: gradle build
      - run:
          name: Add Build Artifacts
          command: |
            mkdir /tmp/artifacts
            cp -r build/distributions /tmp/artifacts
            cp -r build/libs /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts